apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}-nginx
